name: Deploy .NET 8 API to Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "./CICDTwo/CICDTwo/CICDTwo.csproj"

      - name: Build the project
        run: dotnet build "./CICDTwo/CICDTwo/CICDTwo.csproj" --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish "./CICDTwo/CICDTwo/CICDTwo.csproj" --configuration Release --output ./publish --no-build

      - name: Archive Published Files
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Published Files
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Copy files to Windows Server (`D:\CICD`)
        run: |
          net use Z: \\103.24.202.137\C$ /user:mfsadmin "V%pI1aLgqUz(5ne"
          robocopy ./publish Z:\CICD /E /NFL /NDL /NJH /NJS /NC /NS
          net use Z: /delete
