name: Deploy .NET 8 API to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./CICDTwo/CICDTwo.csproj  # Specify the correct path to the .csproj file

      - name: Build the project
        run: dotnet build ./CICDTwo/CICDTwo.csproj --configuration Release  # Specify the .csproj file

      - name: Publish the project
        run: dotnet publish ./CICDTwo/CICDTwo.csproj --configuration Release --output ./publish  # Specify the .csproj file

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 37159
          source: './publish/*'
          target: '/path/to/your/iis/site'

      - name: Restart IIS site
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 37159
          script: |
            iisreset /restart
