name: Deploy .NET 8 API to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Debug - List all files and check path
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing all files recursively:"
          Get-ChildItem -Path . -Recurse -Name
          echo "Checking if .csproj exists:"
          if (Test-Path "cicdTwo/CICDTwo/CICDTwo/CICDTwo.csproj") { echo "Project file found!" } else { echo "Project file NOT found"; exit 1 }

      - name: Restore dependencies
        run: |
          cd "cicdTwo/CICDTwo/CICDTwo"
          dotnet restore "CICDTwo.csproj"

      - name: Build the project
        run: |
          cd "cicdTwo/CICDTwo/CICDTwo"
          dotnet build "CICDTwo.csproj" --configuration Release

      - name: Publish the project
        run: |
          cd "cicdTwo/CICDTwo/CICDTwo"
          dotnet publish "CICDTwo.csproj" --configuration Release --output ../../publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to IIS server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 37159
          source: './publish/*'
          target: 'D:/inetpub/wwwroot/MyApp'

      - name: Restart IIS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 37159
          script: |
            iisreset /restart
